CREATE TABLE `Persons` (
  `PersonID` INT NOT NULL,
  `LastName` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `FirstName` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Address` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `City` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `Gender` TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (`PersonID`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=UTF8MB4 DEFAULT COLLATE=UTF8MB4_GENERAL_CI;

